### ISSUE TITLE
Unhandled error

### ISSUE THREAD

**Issue by arnisoph** [emersion/go-imap-move#11]
IIRC the error return object of Move() is nil even though the IMAP command was not successful. I was accidentely passing a SeqSet with UIDs to Move() instead of UidMove().

Sorry for not providing further details. Please ping me if you want more proper steps to reproduce.

**Comment by emersion** [comment]
The server might just not return an error. Need client debug logs to figure out whether this is a go-imap-move bug.

**Comment by arnisoph** [comment]
ouh, it became very late last night, sorry. Of course that's not a MOVE bug. :D
