### ISSUE TITLE
response has not been handled with Exchange servers

### ISSUE THREAD

**Issue by jedisct1** [emersion/go-imap-move#2]
Exchange servers support the `MOVE` extension:
```
CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=NTLM AUTH=GSSAPI SASL-IR UIDPLUS MOVE ID UNSELECT XPROXY3 CLIENTNETWORKPRESENCELOCATION CHILDREN IDLE NAMESPACE LITERAL+
```

However, trying to use the command via `go-imap-move` fails.

Example with `UidMove`:
```
r9XMqg UID MOVE 1 INBOX
* OK [COPYUID 14  ]
r9XMqg OK MOVE completed.
imap/client: 2017/02/14 01:00:40 response has not been handled: &{* OK COPYUID [14  ] }
```

Example with `Move`:
```
wZFgvA MOVE 1 INBOX
* OK [COPYUID 14 3253 128741]
* 1 EXPUNGE
* 1 EXISTS
wZFgvA OK MOVE completed.
imap/client: 2017/02/14 01:01:15 response has not been handled: &{* OK COPYUID [14 3253 128741] }
```

**Comment by emersion** [comment]
Hi,

The `OK [COPYUID]` response is defined in the extension `UIDPLUS` extension, it isn't supported. Thus, it is just ignored.

The `MOVE` command doesn't require this other extension so it should just work, even if this warning is printed. You can disable it if you want.
