### ISSUE TITLE
How to move one specific mail

### ISSUE THREAD

**Issue by hujiko** [emersion/go-imap-move#9]
Hello,

I am currently loading multiple messages at once and checking their content.
When a message can be handled automatically, I want to move it into folder A, if not, then into folder B.

My code looks something like this:

```
seqSet := new(imap.SeqSet)
	seqSet.AddRange(from, to)

	// Get the whole message body
	var section imap.BodySectionName
	items := []imap.FetchItem{section.FetchItem()}

	messages := make(chan *imap.Message, 1)
	go func() {
		if err := c.Fetch(seqSet, items, messages); err != nil {
			log.Fatal(err)
		}
	}()

for msg := range messages {
  if parsable(msg) {
    mover := move.NewClient(c)
    mover.MoveWithFallback(seqSet, "success-dir")
  }
}
```

But this code moves all selected messages.

I would have expected a function, that takes a message or a message UID as parameter and moves only that specific one.

Or how can I realize that?

**Comment by emersion** [comment]
Provide a `SeqSet` that only contains one message?

**Comment by hujiko** [comment]
But then I need to figure out, which message was which position in the original SeqSet.

I also tried using the Uid ```msg.Uid``` but it always is ```0```

**Comment by emersion** [comment]
Use `msg.SeqNum`

**Comment by emersion** [comment]
Use `msg.SeqNum`
